export const GET_GOOGLE_AUTH_REQUEST = "GET_GOOGLE_AUTH_REQUEST";
export const GET_GOOGLE_AUTH_SUCCESS = "GET_GOOGLE_AUTH_SUCCESS";
export const GET_GOOGLE_AUTH_FAIL = "GET_GOOGLE_AUTH_FAIL";
export const GET_GOOGLE_AUTH_RESET = "GET_GOOGLE_AUTH_RESET";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const GET_PROFILE_RESET = "GET_PROFILE_RESET";

export const AUTH_CHECK_REQUEST = "AUTH_CHECK_REQUEST";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_FAIL = "AUTH_CHECK_FAIL";
export const AUTH_CHECK_RESET = "AUTH_CHECK_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_RESET = "LOGOUT_RESET";

