export const POST_STREAK_REQUEST = "POST_STREAK_REQUEST";
export const POST_STREAK_SUCCESS = "POST_STREAK_SUCCESS";
export const POST_STREAK_FAIL = "POST_STREAK_FAIL";


export const GET_STREAK_REQUEST = "GET_STREAK_REQUEST";
export const GET_STREAK_SUCCESS = "GET_STREAK_SUCCESS";
export const GET_STREAK_FAIL = "GET_STREAK_FAIL";
