export const POST_STREAK_REQUEST = "POST_STREAK_REQUEST";
export const POST_STREAK_SUCCESS = "POST_STREAK_SUCCESS";
export const POST_STREAK_FAIL = "POST_STREAK_FAIL";


export const GET_STREAK_REQUEST = "GET_STREAK_REQUEST";
export const GET_STREAK_SUCCESS = "GET_STREAK_SUCCESS";
export const GET_STREAK_FAIL = "GET_STREAK_FAIL";


export const GET_DETAIL_STREAK_REQUEST = "GET_DETAIL_STREAK_REQUEST";
export const GET_DETAIL_STREAK_SUCCESS = "GET_DETAIL_STREAK_SUCCESS";
export const GET_DETAIL_STREAK_FAIL = "GET_DETAIL_STREAK_FAIL";


export const ADD_STREAK_COUNT_REQUEST = "ADD_STREAK_COUNT_REQUEST";
export const ADD_STREAK_COUNT_SUCCESS = "ADD_STREAK_COUNT_SUCCESS";
export const ADD_STREAK_COUNT_FAIL = "ADD_STREAK_COUNT_FAIL";

export const GET_AI_PROMPT_REQUEST = "GET_AI_PROMPT_REQUEST";
export const GET_AI_PROMPT_SUCCESS = "GET_AI_PROMPT_SUCCESS";
export const GET_AI_PROMPT_FAIL = "GET_AI_PROMPT_FAIL";

export const DELETE_STREAK_REQUEST = "DELETE_STREAK_REQUEST";
export const DELETE_STREAK_SUCCESS = "DELETE_STREAK_SUCCESS";
export const DELETE_STREAK_FAIL = "DELETE_STREAK_FAIL";


export const UPDATE_STREAK_REQUEST = "UPDATE_STREAK_REQUEST";
export const UPDATE_STREAK_SUCCESS = "UPDATE_STREAK_SUCCESS";
export const UPDATE_STREAK_FAIL = "UPDATE_STREAK_FAIL";
