export const POST_STREAK_REQUEST = "POST_STREAK_REQUEST";
export const POST_STREAK_SUCCESS = "POST_STREAK_SUCCESS";
export const POST_STREAK_FAIL = "POST_STREAK_FAIL";


export const GET_STREAK_REQUEST = "GET_STREAK_REQUEST";
export const GET_STREAK_SUCCESS = "GET_STREAK_SUCCESS";
export const GET_STREAK_FAIL = "GET_STREAK_FAIL";


export const GET_DETAIL_STREAK_REQUEST = "GET_DETAIL_STREAK_REQUEST";
export const GET_DETAIL_STREAK_SUCCESS = "GET_DETAIL_STREAK_SUCCESS";
export const GET_DETAIL_STREAK_FAIL = "GET_DETAIL_STREAK_FAIL";


export const ADD_STREAK_COUNT_REQUEST = "ADD_STREAK_COUNT_REQUEST";
export const ADD_STREAK_COUNT_SUCCESS = "ADD_STREAK_COUNT_SUCCESS";
export const ADD_STREAK_COUNT_FAIL = "ADD_STREAK_COUNT_FAIL";